### ISSUE TITLE
Needs moar code

### ISSUE THREAD

**Issue by joshka** [adamralph/bau#1] opened 2013-12-07 14:29 UTC
http://adamralph.com/2013/05/18/oss-it-already/ ;)

**Comment by adamralph** [comment] 2013-12-07 14:55
Lol. Good point. However if you take a look at my fork on the 'initial'
branch you can see that I did OSS it already ;-). I realise that's a little
hidden away but what was intended as an initial spike is actually growing
into the real product. I'm battling with Heathrow right now but I'll get
things merged into the main repo as soon as I have a chance.

**Comment by joshka** [comment] 2013-12-07 15:19
No worries. Just stirring. Meant no offence. Safe travels.

**Comment by adamralph** [comment] 2013-12-07 15:22
None taken :-)

**Comment by adamralph** [comment] 2013-12-08 10:27
closed by #3 :smile:

**Closed as completed by adamralph** 2013-12-08 10:27 UTC
Labels: discussion
